### ISSUE TITLE
Attribute Specific Metadata

### ISSUE THREAD

**Issue by boshrin** [ciferproject/cifer#2]
Possible metadata to attach to attributes:

* Last update time
* Release policy (eg: FERPA)
* Source (eg: SOR)
* Assurance
* Calculated (flag to indicate the attribute is calculated somehow)

**Comment by khazelton** [comment]
Assurance is the only item of metadata not covered by issue #5 with the exception that assurance was not included on #5.  I added assurance there as a comment and suggest we close issue #2.

**Comment by khazelton** [comment]
Proposed resolution we close this issue as resolved.

**Comment by khazelton** [comment]
Point 7 added to issue #5, rest of 2 is duplicated in #5
